from PIL import Image
from io import BytesIO
from base64 import b64decode


def image64toImage(image64):
	return Image.open(BytesIO(b64decode(image64)))


# Material icons (brightness_2 - looks like moon)
# base64 versions used because of pyinstaller not packing them into one executable without using temporary dirs
_disabledDark64 = 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABG0lEQVR4AeWSAQTCQBiFhyHAEEIIAQJACANCCCGEIUAIAUIYIASAAUKAECDAMAxhCGEYhhBCGNbDw8nO6R9QPx/ss/fc3W/95pRlaYMxCEACUhKCHXDrFuyBaSIwqHOCrRI2AR3gAh/k/F6ARZ2TBAxKgaN8b7CIIyxhUMyQTYWf0RV1rqvPkAdwKrxPH1nSUU4x15wyp3elBUsGHDTep99JC4YMSDTepQ+lBV0GpBrfUb2koM2AzOxlBT0GxIZNi6QFnuGR1/SBtODIAK/C2eBGP5Q+cAFeoFnhFwy/AltScNLtONezoB9Jwlf8+Q5aH26uhPuScD4c75b7zuCL4rbA/jb8AEyTgql0axywBGfwVEIzbpQHGtZfzBufjEvSEVBI6QAAAABJRU5ErkJggg=='
_disabledLight64 = 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAABCUlEQVR4AeXSAUQDYRTA8WEYYAghDAECQAgHhBBCCMMAIQQI4QAhAAwQBhgCBBiGIQwhHIYhhBAOrx8WOdPxAPXnBz58vPc6f7Yup4xZUm3MuKdA+R6IFnOOSNXljtg4Y0BByZqg5pJ0Y4KKPt/1KAnIf9JjQXBLswuCmvS4Dgne6dOsJJiTbkEwolmPNUFBqiuCCdsqCe5JdUywZFsFwYxU+wQV2xoQVKTaI1jl3ts7IFi0XNqcVMOWJd8QjEk1JRjSrMsrwXF2wTWf7NDskuCFbifR4y83XlATnHQSXRO8scvPRtQEZSfRDdGY7YARz8TGXWY0E6JFxTmp+lzxxAexsWLKkB7/oC/x72qXmmILIQAAAABJRU5ErkJggg=='
_enabledDark64 = 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAtklEQVR4AeXSEbBCURCA4QNB+HwePnw+QZAFQRjmEwRhGAb5XAzCIAyDIAzCCzmFwZfT3bZJ6vM5/+yeLZ8JLQxR4YwaNQ5YofdqYK3ZEd38BCw1u2NSslCJyUXQxik2SX5dHTHHkhWcQvq6MBWzygb6Yg7ZwJ+YOhv4FXPNBv7fekkYi6myga2YfvaD75pd0MoEdmIGmcdnYhaZx+dilk+vBhvNaoxKBn4wxR43AFyxxRjt8hUe5ItSphPGl5oAAAAASUVORK5CYII='
_enabledLight64 = 'iVBORw0KGgoAAAANSUhEUgAAABgAAAAYCAYAAADgdz34AAAAuElEQVR4AeXTERBCQRAG4A+CMJ8wzCcIsiAIw3yCIAzDIJ+HQRiEYRCEQRjkFAYviZJ29k1S38zq/rd3t35WDUMUOOP6qgNW6KlojfJDHdGtMsEyEPLARJ4CZaDSIXWcgpN0JXWCUxzlOQVDepKmwYCVpH4w4CCpFQy4SmoGA26S2t/+SeNgQCFpGwzoZx/4EWh+QU3CLnj6gYRZsPlCwjzYfJm5mk1wqUaSGphij/vbIm0xRt1feAKp5L4QpFfsjgAAAABJRU5ErkJggg=='

disabledDark = image64toImage(_disabledDark64)
disabledLight = image64toImage(_disabledLight64)
enabledDark = image64toImage(_enabledDark64)
enabledLight = image64toImage(_enabledLight64)
